FROM node:20-alpine AS build
COPY . /app/
WORKDIR /app/
RUN npm ci
WORKDIR /app/
RUN npm run build

FROM busybox:latest AS deploy
WORKDIR /apptemp
COPY --from=build /app/build/client /apptemp

CMD ["/bin/sh", "-c", "mkdir -p /var/www/bonnybonnybonaktan.xyz && cp -R /apptemp/* /var/www/bonnybonnybonaktan.xyz"]
