FROM nginx:alpine
RUN adduser -D -H -u 1001 -s /sbin/nologin webuser
RUN mkdir -p /app/www
RUN chown -R webuser:webuser /app/www && \
    chmod -R 755 /app/www && \
    chown -R webuser:webuser /var/cache/nginx && \
    chown -R webuser:webuser /var/log/nginx && \
    chown -R webuser:webuser /etc/nginx/conf.d && \
    touch /var/run/nginx.pid && \
    chown -R webuser:webuser /var/run/nginx.pid && \
    chmod -R 777 /etc/nginx/conf.d
EXPOSE 443

COPY nginx.conf /etc/nginx/nginx.conf