FROM node:20-alpine AS build
COPY . /app/
WORKDIR /app/
RUN npm ci
WORKDIR /app/
RUN npm run build

FROM nginx:alpine AS serve
RUN adduser -D -H -u 1001 -s /sbin/nologin webuser
RUN mkdir -p /app/bonnybonnybonaktan.xyz
RUN chown -R webuser:webuser /app/bonnybonnybonaktan.xyz && \
    chmod -R 755 /app/bonnybonnybonaktan.xyz && \
    chown -R webuser:webuser /var/cache/nginx && \
    chown -R webuser:webuser /var/log/nginx && \
    chown -R webuser:webuser /etc/nginx/conf.d && \
    touch /var/run/nginx.pid && \
    chown -R webuser:webuser /var/run/nginx.pid && \
    chmod -R 777 /etc/nginx/conf.d 
EXPOSE 443
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/build /app/bonnybonnybonaktan.xyz

